### ISSUE TITLE
Operation Error

### ISSUE THREAD

**Issue by Dozingfiretruck** [lvgl/lv_sim_visual_studio#19]
![image](https://user-images.githubusercontent.com/24759100/107399704-00c43300-6b3c-11eb-943e-fc44a30fa63a.png)
Hi, I'm using VS2019 to run an error alert

**Comment by Dozingfiretruck** [comment]
LVGL.Core.lib Not a valid Win32 application

**Comment by MouriNaruto** [comment]
You need to set the LVGL.Windows.Desktop project as the startup project.
LVGL.Core and LVGL.Examples are the static library projects.

**Comment by Dozingfiretruck** [comment]
Thank you very much.Happy new year.
