### ISSUE TITLE
Help getting started - PDB API call failed, error code C1090

### ISSUE THREAD

**Issue by ilijamr** [lvgl/lv_sim_visual_studio#22]
MS Visual Studio 2019 on x64 machine using latest version (pulled, submodules updated with --init --recursive). Every time it reports an error in a different LVGL source file (using LVGL.Windows instead LVGL.Core and LVGL.Examples). Any advice?

**Comment by MouriNaruto** [comment]
What about your Visual Studio 2019 version?
Maybe you can get help from https://developercommunity.visualstudio.com/t/fatal-error-c1090-pdb-api-call-failed-error-code-3/552999.

**Comment by ilijamr** [comment]
Thanks, found solution there: Under the C/C++ properties for the Project select 'Command Line' and add /FS under 'Additional Options'.
