### ISSUE TITLE
Why do I display "Not a valid Win32 application"?

### ISSUE THREAD

**Issue by TaXue-DuBa** [lvgl/lv_sim_visual_studio#24]
First,I copied the "lvgl" and "lvgl_examples" into "LVGL.Windows/lvgl" and "LVGL.Windows/lvgl_examples" directories.
Then,I used the Visual Studio 2019 and double click the "LVGL.Simulator.sln" to open the VS2019.
Select the x64 and Local Windows Debugger in the top bar.
The compilation seemed to go smoothly.
Finally,the VS2019 shows “"lv_sim_visual_studio-master\Output\Debug\x64\LVGL.Windows.lib" Not a valid Win32 application".

**Comment by MouriNaruto** [comment]
Please set the LVGL.Windows.Desktop project as the startup project.

**Comment by TaXue-DuBa** [comment]
Thank you very much for your answer!

This is my first time using VS2019 and I was not aware of the existence of "startup option".
I noticed that your README.md already stated it, but I didn't notice it.
I set "LVGL.Windows.Simulator" as "Start the project ".
It worked perfectly.
I'm really sorry for the trouble caused to you. Thank you very much for recovering me and solving my big problem.
Thank you very much!

**Comment by MouriNaruto** [comment]
But I think I will merge the projects in the recent days.

**Comment by TaXue-DuBa** [comment]
> But I think I will merge the projects in the recent days.

I think that's great, because then this problem doesn't arise.

**Comment by MouriNaruto** [comment]
@TaXue-DuBa You can try the latest commit.
