### ISSUE TITLE
How to zoom in the latest version 

### ISSUE THREAD

**Issue by littepointR** [lvgl/lv_sim_visual_studio#25]

**Comment by littepointR** [comment]
#define MONITOR_ZOOM is invalid

**Comment by MouriNaruto** [comment]
MONITOR_ZOOM is not supported in the latest version because we changed the backend from SDL to Win32 native. But I will try to add MONITOR_ZOOM feature in the recently commits.

**Comment by MouriNaruto** [comment]
You can try WIN32DRV_MONITOR_ZOOM, it's as similar as MONITOR_ZOOM.
Issue is solved.

**Comment by littepointR** [comment]
Thinks!
