### ISSUE TITLE
visual_studio Compilation fails

### ISSUE THREAD

**Issue by zhuxie99** [lvgl/lv_sim_visual_studio#26]
![图片](https://user-images.githubusercontent.com/21125919/114981263-472d6980-9ec0-11eb-815e-cdfdcd6816bf.png)

I followed the instructions to clone ,and Build &run ,but failed,The error is shown in the figure above

**Comment by zhuxie99** [comment]
i use Visual Studio 2019

**Comment by zhuxie99** [comment]
![图片](https://user-images.githubusercontent.com/21125919/114983116-cc198280-9ec2-11eb-9595-c256a4aa2e80.png)
Error message in English environment

**Comment by MouriNaruto** [comment]
Which the branch you used?

**Comment by zhuxie99** [comment]
I use this command to clone git clone --recurse-submodules https://github.com/lvgl/lv_sim_visual_studio.git

i think master branch

**Comment by MouriNaruto** [comment]
@zhuxie99 I had clone the repo to the other folder just now and compiled successfully.
![image](https://user-images.githubusercontent.com/10867563/114997485-764cd680-9ed2-11eb-9b58-2b581e7559cd.png)

Here is my command list.

> git clone https://github.com/lvgl/lv_sim_visual_studio
> cd lv_sim_visual_studio
> git submodule update --init --recursive
> BuildAllTargets.cmd

I also wonder to know which Visual Studio version you are using.

**Comment by zhuxie99** [comment]
![图片](https://user-images.githubusercontent.com/21125919/114998101-320e0600-9ed3-11eb-8b7a-0286f425eae3.png)

我按照你的命令重新试一遍，之前是一条命令执行，现在分两条命令在试一下

**Comment by MouriNaruto** [comment]
Note: Visual Studio compilation result.
![image](https://user-images.githubusercontent.com/10867563/114998188-47833000-9ed3-11eb-976f-c7a458bfef4e.png)
![image](https://user-images.githubusercontent.com/10867563/114998230-55d14c00-9ed3-11eb-8803-4938d1593776.png)

**Comment by MouriNaruto** [comment]
> ![图片](https://user-images.githubusercontent.com/21125919/114998101-320e0600-9ed3-11eb-8b7a-0286f425eae3.png)
> 
> 我按照你的命令重新试一遍，之前是一条命令执行，现在分两条命令在试一下

我感觉还是老版本 Visual Studio 2019 提供的 MSVC 工具链的警告策略和新版本不同的关系。
倒是我习惯用 /W4 /WX 了，也就是 Level 4 警告且视警告为错误，我感觉可以把 /WX 去掉，也许你就可以编译了

**Comment by zhuxie99** [comment]
我之前试过了，还是编译不通过，现在我正在更新vs版本到最新版

**Comment by MouriNaruto** [comment]
> 我之前试过了，还是编译不通过，现在我正在更新vs版本到最新版

去除 /WX 的事情最好直接在 vcxproj 修改，毕竟我对 vcxproj 进行了精简，否则要同时支持四个架构（x86 x64 arm32 arm64）各两种配置（Debug Release）会比较乱

**Comment by zhuxie99** [comment]
你那边如果把 /WX开启，是否会出现这些警告和错误

**Comment by zhuxie99** [comment]
感谢，我把vs升级到最新版本，可以编译通过了，能正常运行了

**Comment by MouriNaruto** [comment]
v8 的适配分支已经使用 Level3 且不视警告为错误编译
当主分支（v7 适配分支）也这样调整后，我会自动关闭 issue，希望理解
