### ISSUE TITLE
For using the the lvgl (v8) examples

### ISSUE THREAD

**Issue by ataweg** [lvgl/lv_sim_visual_studio#28]
please add 
`#include "lvgl/examples/lv_examples.h"`
to LVGL_Simulator.cpp and you can use the lvgl examples.
Most of the examples are ok, but there are some with issues. For now these are:
lv_example_slider_2();
lv_example_slider_3();
lv_example_bar_6();

see also https://gist.github.com/ataweg/46f3b5b928aefa484d02877e922ce0d4

**Comment by MouriNaruto** [comment]
Thanks. I want to borrow something from your link.
I will test some examples you said which have issues. (And upgrade LVGL submodules for trying to solve the issue.)

**Comment by kisvegabor** [comment]
@ataweg 
I've fixed the mentioned examples.

**Comment by MouriNaruto** [comment]
The mentioned examples seem to be fixed after I upgrade the LVGL submodules.
https://github.com/lvgl/lv_sim_visual_studio/commit/faac4b025661e50d23629958b67ad73384ab1f0d.

**Comment by MouriNaruto** [comment]
It looks the issue is solved. I think it's time to close the issue. If have any question, please reply to this issue.
