### ISSUE TITLE
Small bug with Slider control ?

### ISSUE THREAD

**Issue by geoffw123** [lvgl/lv_sim_visual_studio#34]
Hi
I am guessing this is a V8 simulator bug with the slider ?  The light blue semi circles at the end of the slider background are not drawing properly ?  I havent tried this with V8 on my hardware, so cant say if its specific to simulator or not. See attached screenshot.
![bugMaybe](https://user-images.githubusercontent.com/32308347/131250671-75ceeb3b-f0bc-4309-ba71-74424da9760e.png)

**Comment by kisvegabor** [comment]
It was a bug in lvgl master a few weeks ago. Updating lvgl should solve the issue.

**Comment by MouriNaruto** [comment]
I have update all submodules in this repo. I hope this issue can be solved.

**Comment by geoffw123** [comment]
Thanks for the speedy update. Confirmed fixed for me

**Comment by MouriNaruto** [comment]
It seems to be OK to close this issue.
