### ISSUE TITLE
lv_style_set_text_font

### ISSUE THREAD

**Issue by LightgardenCC** [lvgl/lv_sim_visual_studio#37]
错误	LNK2001	无法解析的外部符号 "struct _lv_font_t test" (?test@@3U_lv_font_t@@A)	LVGL.Simulator ....\usr_test.obj	1

**Comment by priceee** [comment]
你好！请问这个问题你是怎么解决的？我在使用lvgl设置图片源的时候也报了这样的错。

**Comment by MakeLTHer** [comment]
你好请问解决了吗  我现在也遇到这个问题
