### ISSUE TITLE
[readme] 需要在readme中提示用户将此处修改为x86配置 | need to remind users to adjust here to x86

### ISSUE THREAD

**Issue by mysterywolf** [lvgl/lv_sim_visual_studio#38]
![image](https://user-images.githubusercontent.com/34888354/146305465-92a64a6c-b4b4-43a2-a93a-c1bc9a044850.png)
需要在readme中提示用户将此处修改为x86配置，以适配自己的PC平台. 否则可能会出现报错.

**Comment by kisvegabor** [comment]
I'm on Linux and don't use Visual Studio. Could you add PR with a screenshot?

**Comment by MouriNaruto** [comment]
I will add some notices in the readme.

Because the simulator project support arm64, Visual Studio will choose arm64 in the first time because of the alphabetical order.

Kenji Mouri

**Comment by MouriNaruto** [comment]
@mysterywolf @kisvegabor 

I have added the notice.
https://github.com/lvgl/lv_sim_visual_studio/commit/39bcda3f1c98f8145dd80d5acc73b535b403640b

Kenji Mouri

**Comment by mysterywolf** [comment]
Thank you~
