### ISSUE TITLE
display error with indexed image

### ISSUE THREAD

**Issue by fo2w** [lvgl/lv_sim_visual_studio#43]
branch: master

code to reproduce:
```c
    // img_name_map is a c_array here with raw data
    // I random pick a PNG file and use the online tool (https://lvgl.io/tools/imageconverter) to generate it

    const lv_img_dsc_t img_name = {
      .header.cf = LV_IMG_CF_INDEXED_4BIT,
      .header.always_zero = 0,
      .header.reserved = 0,
      .header.w = 40,
      .header.h = 40,
      .data_size = 864,
      .data = img_name_map,
    };

    LV_IMG_DECLARE(img_name);
    lv_obj_t* icon = lv_img_create(lv_scr_act());
    lv_img_set_src(icon, &img_name);
    lv_obj_set_size(icon, 40, 40);
```

expected result:
show the CORRECT image on the top left of the main window

actual result:
![image](https://user-images.githubusercontent.com/1845057/170088851-f2c78aaf-b23d-47c1-8b92-f20cafbcb354.png)

**Comment by kisvegabor** [comment]
Is it related to the windows port or LVGL in general?

**Comment by MouriNaruto** [comment]
@kisvegabor @fo2w

I have reproduced the issue and solved it by updating the LVGL version to the latest.

![image](https://user-images.githubusercontent.com/10867563/170386709-a9a537c6-ed3d-42d9-9d3b-22c27e552a0f.png)

Kenji Mouri

**Comment by fo2w** [comment]
By updating the LVGL version to the latest, now it works well.
Thank you guys.
